// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PiecebyPiece.Models;

#nullable disable

namespace PiecebyPiece.Migrations
{
    [DbContext(typeof(PiecebyPieceDBContext))]
    partial class PiecebyPieceDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PiecebyPiece.Models.mADMIN", b =>
                {
                    b.Property<int>("adminID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("adminID"));

                    b.Property<string>("adminEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adminName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("adminPassword")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("adminSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("adminID");

                    b.ToTable("dAdmin");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mCERTIFICATE", b =>
                {
                    b.Property<int>("cerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("cerID"));

                    b.Property<DateTime>("cerDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("courseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("enrollID")
                        .HasColumnType("int");

                    b.Property<int?>("userID")
                        .HasColumnType("int");

                    b.Property<string>("userName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userSurname")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("cerID");

                    b.HasIndex("enrollID")
                        .IsUnique();

                    b.HasIndex("userID");

                    b.ToTable("dCertificate");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mCOURSE", b =>
                {
                    b.Property<int>("courseID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("courseID"));

                    b.Property<string>("courseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("coursePhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("courseSubject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("courseID");

                    b.ToTable("dCourse");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mENROLLMENT", b =>
                {
                    b.Property<int>("enrollID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("enrollID"));

                    b.Property<int>("courseID")
                        .HasColumnType("int");

                    b.Property<string>("courseName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("enrollStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("enrollTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("enrollID");

                    b.HasIndex("courseID");

                    b.HasIndex("userID");

                    b.ToTable("dEnrollment");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mLESSON", b =>
                {
                    b.Property<int>("lessonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("lessonID"));

                    b.Property<int>("courseID")
                        .HasColumnType("int");

                    b.Property<string>("lessonDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("lessonName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<float>("lessonProgress")
                        .HasColumnType("real");

                    b.HasKey("lessonID");

                    b.HasIndex("courseID");

                    b.ToTable("dLesson");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mLESSONPROGRESS", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("courseID")
                        .HasColumnType("int");

                    b.Property<int>("enrollID")
                        .HasColumnType("int");

                    b.Property<bool>("isPassedTest")
                        .HasColumnType("bit");

                    b.Property<DateTime>("lastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("lessonID")
                        .HasColumnType("int");

                    b.Property<float>("progressPercent")
                        .HasColumnType("real");

                    b.Property<int>("userID")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("enrollID");

                    b.HasIndex("lessonID");

                    b.HasIndex("userID");

                    b.ToTable("dLessonProgress");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mQUESTION", b =>
                {
                    b.Property<int>("questionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionID"));

                    b.Property<string>("choiceA")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("choiceB")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("choiceC")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("choiceD")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("correctAnswer")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("questionPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("questionText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("testID")
                        .HasColumnType("int");

                    b.HasKey("questionID");

                    b.HasIndex("testID");

                    b.ToTable("dQuestion");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mTEST", b =>
                {
                    b.Property<int>("testID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("testID"));

                    b.Property<int>("lessonID")
                        .HasColumnType("int");

                    b.Property<int?>("mLESSON")
                        .HasColumnType("int");

                    b.Property<float>("testScore")
                        .HasColumnType("real");

                    b.HasKey("testID");

                    b.HasIndex("lessonID")
                        .IsUnique();

                    b.ToTable("dTest");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mUSER", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("userID"));

                    b.Property<string>("userEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("userPassword")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("userPhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("userSurname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("userID");

                    b.ToTable("dUser");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mVideoEP", b =>
                {
                    b.Property<int>("vdoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("vdoID"));

                    b.Property<string>("epFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("epProgress")
                        .HasColumnType("real");

                    b.Property<int>("lessonID")
                        .HasColumnType("int");

                    b.Property<int?>("mLESSON")
                        .HasColumnType("int");

                    b.Property<string>("vdoFilePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vdoName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("vdoID");

                    b.HasIndex("lessonID");

                    b.ToTable("dVideoEP");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mCERTIFICATE", b =>
                {
                    b.HasOne("PiecebyPiece.Models.mENROLLMENT", "Enrollment")
                        .WithOne("Certificate")
                        .HasForeignKey("PiecebyPiece.Models.mCERTIFICATE", "enrollID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiecebyPiece.Models.mUSER", "User")
                        .WithMany("Certificates")
                        .HasForeignKey("userID");

                    b.Navigation("Enrollment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mENROLLMENT", b =>
                {
                    b.HasOne("PiecebyPiece.Models.mCOURSE", "Course")
                        .WithMany("Enrollments")
                        .HasForeignKey("courseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiecebyPiece.Models.mUSER", "User")
                        .WithMany("Enrollments")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mLESSON", b =>
                {
                    b.HasOne("PiecebyPiece.Models.mCOURSE", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("courseID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mLESSONPROGRESS", b =>
                {
                    b.HasOne("PiecebyPiece.Models.mENROLLMENT", "Enrollment")
                        .WithMany()
                        .HasForeignKey("enrollID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PiecebyPiece.Models.mLESSON", "Lesson")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("lessonID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PiecebyPiece.Models.mUSER", "User")
                        .WithMany("LessonProgresses")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Enrollment");

                    b.Navigation("Lesson");

                    b.Navigation("User");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mQUESTION", b =>
                {
                    b.HasOne("PiecebyPiece.Models.mTEST", "Test")
                        .WithMany("Questions")
                        .HasForeignKey("testID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Test");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mTEST", b =>
                {
                    b.HasOne("PiecebyPiece.Models.mLESSON", "Lesson")
                        .WithOne("Test")
                        .HasForeignKey("PiecebyPiece.Models.mTEST", "lessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mVideoEP", b =>
                {
                    b.HasOne("PiecebyPiece.Models.mLESSON", "Lesson")
                        .WithMany("VideoEPs")
                        .HasForeignKey("lessonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mCOURSE", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mENROLLMENT", b =>
                {
                    b.Navigation("Certificate");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mLESSON", b =>
                {
                    b.Navigation("LessonProgresses");

                    b.Navigation("Test");

                    b.Navigation("VideoEPs");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mTEST", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("PiecebyPiece.Models.mUSER", b =>
                {
                    b.Navigation("Certificates");

                    b.Navigation("Enrollments");

                    b.Navigation("LessonProgresses");
                });
#pragma warning restore 612, 618
        }
    }
}
